export const DEFAULT_SITE_CONTENT = {
  global: {
    brand_name: "MARSHEL",
    brand_descriptor: "/ SOFTWARE × HARDWARE",
    brand_aria_label: "Marshel Software dan Hardware, kembali ke beranda",
    nav_links: [
      { label: "Beranda", href: "/" },
      { label: "Skills & Specs", href: "/skills" },
      { label: "Proyek", href: "/projects" },
      { label: "Kontak", href: "/contact" },
    ],
    resume_button_label: "Resume // CV",
    mobile_menu_open_label: "Menu +",
    mobile_menu_close_label: "Tutup ×",
    footer_text: "BUILT WITH INTENT & CLARITY",
    availability_label: "TERBUKA UNTUK KOLABORASI & PROYEK",
  },
  home: {
    hero_eyebrow: "FULL-STACK DEVELOPMENT / IOT / EMBEDDED SYSTEMS",
    hero_title: "Membangun software yang terhubung dengan dunia nyata.",
    hero_description: "Saya merancang dan membangun aplikasi web berkinerja tinggi, sistem REST API yang modular, serta integrasi hardware IoT—menyatukan antarmuka presisi dengan arsitektur data yang andal.",
    primary_action_label: "Eksplorasi Proyek",
    secondary_action_label: "Profil & Kapabilitas",
    stack_label: "CORE TECH STACK:",
    tech_stack: ["Next.js", "React", "TypeScript", "Node.js", "Python", "ESP32 / IoT", "Docker", "PostgreSQL", "Tailwind CSS"],
    metrics: [
      { value: "AUTO_PROJECT_COUNT", label: "Proyek Terverifikasi" },
      { value: "03", label: "Pilar Rekayasa (Web / API / IoT)" },
      { value: "100%", label: "Fokus pada Clarity & Reliability" },
    ],
    selected_work_eyebrow: "SELECTED WORK",
    selected_work_title: "Sistem nyata yang dibangun dengan presisi.",
    selected_work_description: "Studi kasus bagaimana keputusan antarmuka, efisiensi arsitektur data, dan eksekusi teknis disatukan menjadi solusi yang dapat diandalkan.",
    selected_project_count: 2,
    profile_eyebrow: "ENGINEER PROFILE",
    profile_title: "Menghubungkan antarmuka digital dan dunia perangkat.",
    profile_discipline: "Full-Stack Web & IoT Systems Engineer",
    profile_fallback_bio: "Saya berfokus pada titik temu antara interaksi pengguna, arsitektur data, dan komputasi perangkat. Prinsip saya sederhana: kompleksitas sistem tetap berada di balik layar, menghasilkan pengalaman yang jernih dan andal.",
    cv_action_label: "Lihat CV / Resume",
    principle_label: "ENGINEERING PHILOSOPHY",
    principle_text: "Clarity first. Complexity stays behind the interface.",
    capabilities: [
      { title: "Interface Engineering", description: "Membangun antarmuka modern yang responsif, terstruktur, ramah aksesibilitas, dan memiliki interaksi yang fluid.", tag: "Frontend Systems" },
      { title: "Backend & REST API", description: "Merancang API modular, autentikasi aman, manajemen database relasional, dan integrasi layanan mikro yang scalable.", tag: "Backend Architecture" },
      { title: "IoT & Hardware Integration", description: "Mengintegrasikan mikrokontroler ESP32, sensor telemetri, protokol komunikasi data MQTT/WebSockets, dan dashboard analitik real-time.", tag: "IoT & Embedded" },
    ],
    process_eyebrow: "ENGINEERING WORKFLOW",
    process_title: "Metodologi terstruktur dari analisis hingga deployment.",
    process_description: "Setiap sistem dimulai dari pemahaman masalah yang mendalam, diterjemahkan ke dalam arsitektur yang solid, lalu diuji secara konsisten.",
    process_steps: [
      { title: "Analisis Kebutuhan & Masalah", description: "Memetakan use case, batasan teknis, dan ekspektasi pengguna sebelum menetapkan keputusan teknologi." },
      { title: "Desain Arsitektur & Skema Data", description: "Menentukan alur data, skema database, kontrak API, serta pemisahan modul sebelum penulisan kode dimulai." },
      { title: "Pengembangan Modular & Pengujian", description: "Mengimplementasikan fitur dalam siklus bertahap, memverifikasi edge-case, dan menjaga kebersihan basis kode." },
      { title: "Optimasi, Deployment & Monitoring", description: "Menyiapkan pipeline CI/CD, mengoptimalkan aset performa, dan memastikan sistem siap digunakan di lingkungan produksi." },
    ],
    contact_eyebrow: "START A CONVERSATION",
    contact_title: "Punya ide sistem atau proyek yang ingin direalisasikan?",
    contact_description: "Diskusikan tujuan produk, konteks teknis, atau arsitektur IoT yang Anda butuhkan. Kita mulai dengan memetakan langkah implementasi yang paling efektif.",
    brief_builder_label: "INTERACTIVE PROJECT BRIEF",
    brief_builder_description: "Pilih kategori proyek yang ingin Anda diskusikan:",
    brief_focus_label: "FOKUS",
    brief_expectation_label: "EKSPEKTASI SISTEM",
    brief_action_prefix: "Lanjutkan Diskusi",
    project_types: [
      { id: "web", label: "Web Application", description: "Aplikasi web interaktif dengan performa tinggi, SEO optimal, dan desain responsif." },
      { id: "iot", label: "IoT & Hardware System", description: "Integrasi sensor fisik, mikrokontroler ESP32, telemetri data, dan monitoring dashboard." },
      { id: "backend", label: "Backend API & Database", description: "Arsitektur RESTful API, skema PostgreSQL, sistem autentikasi, dan logika bisnis yang aman." },
      { id: "fullstack", label: "Full Stack End-to-End", description: "Solusi terpadu dari antarmuka frontend, backend API, hingga integrasi database dan server." },
    ],
    telemetry: {
      title: "LIVE TELEMETRY NODE",
      pause_label: "PAUSE",
      live_label: "LIVE",
      node_status_label: "NODE STATUS",
      node_status_value: "ONLINE",
      latency_label: "LATENCY",
      protocol_label: "PROTOCOL",
      protocol_value: "MQTT / WS",
      packets_label: "PACKETS STREAM",
      nodes_value: "NODES: ESP32-S3 / REST API / POSTGRESQL",
    },
  },
  projects: {
    hero_eyebrow: "ENGINEERING REPOSITORY & SHOWCASE",
    hero_title: "Katalog Proyek & Studi Kasus",
    hero_description: "Kumpulan aplikasi web modern, REST API backend, dan integrasi perangkat IoT yang dirancang dengan fokus pada keandalan, kejelasan antarmuka, dan performa.",
    filter_label: "FILTER KATEGORI",
    search_placeholder: "Cari proyek, bahasa, atau tech stack...",
    all_category_label: "Semua Proyek",
    index_eyebrow: "PROJECT DIRECTORY",
    index_title: "Daftar Karya & Repositori",
    displayed_suffix: "DITAMPILKAN",
    card_action_label: "Lihat Studi Kasus →",
  },
  skills: {
    hero_eyebrow: "TECHNICAL EXPERTISE & SPECIFICATIONS",
    hero_title: "Kapabilitas & Spesifikasi Teknis",
    hero_description: "Rekayasa sistem komputasi terpadu: dari arsitektur frontend modern yang responsif, backend API berkinerja tinggi, hingga komunikasi protokol hardware IoT secara presisi.",
    competencies_eyebrow: "DOMAINS / 01",
    competencies_title: "Core Engineering Disciplines",
    specifications_eyebrow: "TECH STACK MATRIX / 02",
    specifications_title: "Technical Stack & Ecosystem Matrix",
    table_headers: ["TEKNOLOGI", "KATEGORI", "LEVEL PENGALAMAN", "STATUS & EKOSISTEM"],
    timeline_eyebrow: "MILESTONES & EXPERIENCE / 03",
    timeline_title: "Perjalanan Rekayasa & Pengalaman",
    milestones: [
      { period: "2024 - SEKARANG", role: "Full Stack & IoT Systems Engineer", description: "Mengembangkan arsitektur web modern Next.js, dashboard telemetri IoT real-time, dan integrasi database performa tinggi." },
      { period: "2023 - 2024", role: "Frontend & Backend Developer", description: "Membangun antarmuka interaktif yang fluid, REST API modular dengan autentikasi berbasis token, serta optimasi query database." },
      { period: "2022 - 2023", role: "Embedded Systems & Hardware Enthusiast", description: "Merancang rangkaian sensor node ESP32/Arduino, protokol komunikasi data nirkabel, dan otomasi perangkat keras." },
    ],
    cta_eyebrow: "KOLABORASI",
    cta_title: "Tertarik membangun sistem bersama?",
    cta_description: "Pelajari bagaimana keahlian teknis ini diaplikasikan langsung pada proyek dan produk nyata.",
    projects_action_label: "Lihat Studi Kasus Proyek →",
    contact_action_label: "Hubungi Saya",
  },
  contact: {
    eyebrow: "COMMUNICATION & INTAKE",
    title: "Mulai Percakapan & Kolaborasi",
    description: "Bagikan tujuan proyek, kebutuhan teknis, atau tantangan yang sedang Anda hadapi. Saya siap membantu mendiskusikan pendekatan arsitektur yang paling tepat.",
    availability_label: "● STATUS: OPEN FOR SELECTED COLLABORATIONS",
    form_eyebrow: "PROJECT BRIEF FORM",
    name_label: "Nama Lengkap",
    name_placeholder: "Contoh: Alex Morgan",
    email_label: "Alamat Email",
    email_placeholder: "nama@perusahaan.com",
    message_label: "Rincian Kebutuhan Proyek",
    message_placeholder: "Jelaskan ruang lingkup proyek, target waktu, atau spesifikasi teknologi yang Anda perlukan...",
    submit_label: "Kirimkan Pesan",
    submitting_label: "Mengirimkan Pesan…",
    success_message: "Pesan berhasil dikirim! Terima kasih atas pesan Anda—saya akan merespons dalam 1x24 jam.",
    error_message: "Pesan gagal dikirim. Silakan periksa koneksi internet Anda atau hubungi lewat email langsung.",
    toast_success: "Pesan berhasil dikirim ke Marshel!",
    toast_error: "Gagal mengirim pesan. Silakan coba beberapa saat lagi.",
    prefill_focus_label: "Fokus Proyek",
    prefill_general_label: "Umum",
    prefill_detail_label: "Detail & Ekspektasi",
    name_required_message: "Nama lengkap wajib diisi.",
    email_required_message: "Alamat email wajib diisi.",
    email_invalid_message: "Mohon gunakan format email yang valid.",
    message_required_message: "Rincian pesan atau brief wajib diisi.",
  },
  project_detail: {
    back_label: "Kembali ke Direktori Proyek",
    demo_label: "Live Demo ↗",
    github_label: "Source Code GitHub ↗",
    about_eyebrow: "STUDI KASUS & LATAR BELAKANG",
    about_fallback_title: "Gambaran Umum, Keputusan Arsitektur & Hasil",
    stack_eyebrow: "SPESIFIKASI & TEKNOLOGI",
    category_label: "Kategori Proyek",
    skills_label: "Teknologi Terkait",
    architecture_eyebrow: "SYSTEM ARCHITECTURE & DATA FLOW",
    architecture_title: "Alur Kerja & Arsitektur Teknis",
    gallery_eyebrow: "DOKUMENTASI VISUAL",
    gallery_title: "Tangkapan Layar & Implementasi",
    gallery_empty_title: "Dokumentasi Belum Tersedia",
    gallery_empty_message: "Proyek ini belum memiliki lampiran dokumentasi visual tambahan.",
  },
  resume: {
    eyebrow: "CURRICULUM VITAE / RESUME",
    title_template: "{name} — Profil Rekayasa & CV",
    tag: "FULL-STACK & IOT ENGINEER",
    version: "VERSI TERVERIFIKASI 2026",
    description: "Dokumentasi kualifikasi rekayasa perangkat lunak, sistem backend REST API, implementasi IoT, dan rekam jejak proyek.",
    highlights: [
      { label: "BIDANG KEAHLIAN", value: "Full-Stack Web, REST API, ESP32 & IoT" },
      { label: "LATAR BELAKANG", value: "Teknik Komputer / Computer Engineering" },
      { label: "FORMAT DOKUMEN", value: "PDF Siap Unduh & Cetak" },
    ],
    download_label: "Unduh CV (PDF) ↓",
    close_label: "Tutup",
    fallback_cv_url: "/Marshel_CV_Fullstack_IoT.pdf",
    download_filename: "Marshel_CV_Engineer.pdf",
  },
};

export type SiteContent = typeof DEFAULT_SITE_CONTENT;

export interface SiteContentRecord {
  id: number;
  content: SiteContent;
  created_at?: string;
  updated_at?: string;
}

export function mergeSiteContent(content?: Partial<SiteContent>): SiteContent {
  return {
    global: { ...DEFAULT_SITE_CONTENT.global, ...content?.global },
    home: {
      ...DEFAULT_SITE_CONTENT.home,
      ...content?.home,
      telemetry: {
        ...DEFAULT_SITE_CONTENT.home.telemetry,
        ...content?.home?.telemetry,
      },
    },
    projects: { ...DEFAULT_SITE_CONTENT.projects, ...content?.projects },
    skills: { ...DEFAULT_SITE_CONTENT.skills, ...content?.skills },
    contact: { ...DEFAULT_SITE_CONTENT.contact, ...content?.contact },
    project_detail: { ...DEFAULT_SITE_CONTENT.project_detail, ...content?.project_detail },
    resume: { ...DEFAULT_SITE_CONTENT.resume, ...content?.resume },
  };
}
